name: Deploy Backend to Vercel
env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
on: 
  push:
    paths: 
      - 'apps/nextapp/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy-prod:
    name: Deploy Backend to Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3
      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./apps/nextapp
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        working-directory: ./apps/nextapp
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./apps/nextapp
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
